DELETE http://localhost:3001/api/persons/6414e1f167f62ac7a6cd2822

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "asd",
    "number": "1234"
}
###
GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/6417b100dbfc4b850b83f2f0

###
PUT http://localhost:3001/api/persons/6417b100dbfc4b850b83f2f0
content-type: application/json

{
    "name": "cambio",
    "number": "777777"
}